name: Halka Arz Tavan Bozma
task: task1
token: 6453858576:AAFlGCnGLqElgh6GNefdwvuow2oVgUuuEqU
params:
  - GIPTA.IS
  - SEKUR.IS
  # - AYCES.IS
  # - TDGYO.IS
  # - EBEBK.IS
  # - ATAGY.IS
  # - ASTOR.IS
  # - DOAS.IS
