name: Hisse Alım/Satım Seviyesine Gelme
task: task2
token: 6321515977:AAGyDfbSr6KoXlU_voILoZRXJESpoNEyUtk
params:
  - ISMEN.IS
  - INFO.IS
  - MGROS.IS
  - BIMAS.IS
  - TAVHL.IS
  - TOASO.IS
  - MAVI.IS
  - ALARK.IS
  - PGSUS.IS
  - THYAO.IS
  - AKBNK.IS
  - GARAN.IS
  - GRSEL.IS
  - PNSUT.IS
  - DOHOL.IS
  - ANHYT.IS
  - KAREL.IS
  - AKGRT.IS
  - GWIND.IS
  - ISCTR.IS
  - TTRAK.IS
  - KCHOL.IS
  - SAYAS.IS
  - KONKA.IS
  - GLYHO.IS
