name: Fon Envanter
enabled: False
task: task3
token: 6615742088:AAFjPXrXk5xpQc1ITSMFNRwxmSEcFoUjHtI
params:
  - KONKA.IS
  - ISCTR.IS
  - ALARK.IS
  - GLYHO.IS
  - TTKOM.IS
  - GWIND.IS
fons:
  - BUY
  - TCD
  - GUM
  - GOH
  - ST1
  - ZFB
