name: Fon Envanter
task: task3
token: 6615742088:AAFjPXrXk5xpQc1ITSMFNRwxmSEcFoUjHtI
params:
  - KONKA.IS
  - PGSUS.IS
  - ISCTR.IS
  - ANSGR.IS
  - DOHOL.IS
  - ISMEN.IS
  - SAFKR.IS
  - KAREL.IS
  - ALARK.IS
  - FROTO.IS
  - GLYHO.IS
  - GRSEL.IS
  - TTKOM.IS
  - BIMAS.IS
  - OSMEN.IS
  - GWIND.IS
fons:
  - BUY
  - TCD
  - GUM
  - GOH
  - ST1
  - ZFB
